---
name: module3_task4
on:
  push:
    branches: [main, master]
  schedule:
    - cron: "0 0 * * *"
  pull_request:
    types: [opened, edited, labeled]

jobs:
  module3_task0:
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup
        run: |
          cd module3_task4/
          sudo ./setup.sh
      - name: lint
        run: |
          cd module3_task4/
          make lint
      - name: build
        run: |
          cd module3_task4/
          make build
      - name: post
        run: |
          cd module3_task4/
          make POST_TITLE="Test" POST_NAME="Test" post
      - name: tests
        run: |
          cd module3_task4/
          make tests
          make validate
          make unit-tests
          make package
          make clean
      - name: release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: 1.0.1
          files: |
            module3_task4/awesome-website.zip
            module3_task4/DEPLOY.md
      - name: archive build
        if: ${{ success()}}
        uses: actions/upload-artifact@v3
        with:
          name: upload-package
          path: module3_task4/awesome-website.zip
