---
name: module3_task0
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  module3_task0:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: cd in to correct directory
        run: |
          cd module3_task0
          make help
      - name : setup for install tools
        run: |
          sudo./setup.sh
      - name : build
          make build
      - name: post
        run: |
          cd module3_task1/
          make POST_TITLE="Test Title" POST_NAME="Test-name" post
      - name: Integration tests
        run: |
          cd module3_task1/
          make integration-tests
      - name: clean
        run: |
          cd module3_task1/
          make clean
